name: HealthCheck

on:
  schedule:
    -cron: '0/5 * * * *'

jobs:
  cron_healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://hidden-savannah-78105.herokuapp.com
          max-attempts: 3
          retry-delay: 5s
